# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 03:41
from __future__ import unicode_literals

import blog_zinnia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_zinnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', blog_zinnia.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
    ]
