# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
